### PR TITLE
Use default json encoder 'str'

### LINKED ISSUE #11: TypeError: Object of type SpecifierSet is not JSON serializable
Sometimes, version fields are now `SpecifierSet`. See https://github.com/dephell/dephell/pull/285 and https://github.com/pypa/setuptools/issues/1889 also related.

```py
> metaextract setuptools-41.4.0.zip 
Traceback (most recent call last):
  File "setup.py", line 149, in <module>
    dist = setuptools.setup(**setup_params)
  File "/tmp/metaextract_ph4xpq3m/setuptools-41.4.0/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/site-packages/metaextract/metaextract.py", line 85, in run
    sort_keys=True))
  File "/usr/lib64/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib64/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SpecifierSet is not JSON serializable
```

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/toabctl/metaextract/issues/11

### CODE REVIEW

**Comment by jayvdb** [comment]
This ignores that py2 should use `unicode`.  I can fix that if requested, but didnt know if it was worthwhile given 2020 is so close, and this is fixing an irregular bug.

**Comment by toabctl** [comment]
Would it be possible to add a test case for that?

**Comment by jayvdb** [comment]
Sure.

**Comment by toabctl** [comment]
@jayvdb thanks for the PR. I also uploaded a new release to pypi which includes this patch

**Comment by jayvdb** [comment]
Thanks, sorry I didnt get around to adding a test case for you.

**Pull request merged**
